"""Core modules for Starsector Automated Modlist Installer."""

from .constants import (
    BASE_DIR, CONFIG_FILE, CATEGORIES_FILE, LOG_FILE, PREFS_FILE, CACHE_DIR,
    URL_VALIDATION_TIMEOUT_HEAD, REQUEST_TIMEOUT, MIN_FREE_SPACE_GB, CHUNK_SIZE,
    MAX_DOWNLOAD_WORKERS, MAX_VALIDATION_WORKERS,
    MAX_RETRIES, RETRY_DELAY, BACKOFF_MULTIPLIER, CACHE_TIMEOUT,
    UI_BOTTOM_BUTTON_HEIGHT, UI_MIN_WINDOW_WIDTH, UI_MIN_WINDOW_HEIGHT,
    UI_DEFAULT_WINDOW_WIDTH, UI_DEFAULT_WINDOW_HEIGHT,
    UI_RIGHT_PANEL_WIDTH, UI_RIGHT_PANEL_MINSIZE, UI_LEFT_PANEL_MINSIZE,
    InstallationReport
)
from .config_manager import ConfigManager
from .installer import ModInstaller
from .archive_extractor import ArchiveExtractor

__all__ = [
    'BASE_DIR', 'CONFIG_FILE', 'CATEGORIES_FILE', 'LOG_FILE', 'PREFS_FILE', 'CACHE_DIR',
    'URL_VALIDATION_TIMEOUT_HEAD', 'REQUEST_TIMEOUT', 'MIN_FREE_SPACE_GB', 'CHUNK_SIZE',
    'MAX_DOWNLOAD_WORKERS', 'MAX_VALIDATION_WORKERS',
    'MAX_RETRIES', 'RETRY_DELAY', 'BACKOFF_MULTIPLIER', 'CACHE_TIMEOUT',
    'UI_BOTTOM_BUTTON_HEIGHT', 'UI_MIN_WINDOW_WIDTH', 'UI_MIN_WINDOW_HEIGHT',
    'UI_DEFAULT_WINDOW_WIDTH', 'UI_DEFAULT_WINDOW_HEIGHT',
    'UI_RIGHT_PANEL_WIDTH', 'UI_RIGHT_PANEL_MINSIZE', 'UI_LEFT_PANEL_MINSIZE',
    'ConfigManager', 'ModInstaller', 'InstallationReport', 'ArchiveExtractor'
]
